#cloud-config
users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIH7O33q/6F88/MdHTk0Sl93DtMjsisYQSjIqK6ES+Mfr
    lock_passwd: false

chpasswd:
  list: |
    ubuntu:123
  expire: false

ssh_pwauth: false
